sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.0
  - 2.3.1
  - 2.2.6
  - 2.1.10
  - 2.0.0
  - jruby
  - rbx-2
gemfile:
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-4.0.x
  - test/gemfiles/Gemfile.rails-4.1.x
  - test/gemfiles/Gemfile.rails-4.2.x
  - test/gemfiles/Gemfile.rails-5.0.x
matrix:
  exclude:
    - { rvm: jruby, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
    - { rvm: rbx-2, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
    - { rvm: 2.0.0, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
    - { rvm: 2.1, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
    - { rvm: 2.2, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
  fast_finish: true
script: "bundle exec rake submodules test"
